version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx:42
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    init: true
    ports:
      - "443:443"
    volumes: 
      - ./requirements/nginx/conf:/etc/nginx/conf.d  # Nginx configuration
      - ./requirements/nginx/certs:/etc/nginx/certs  # SSL certificates
      - ./requirements/nginx/html:/www  # Static HTML files
    env_file:
      - .env
    networks:
      - inception-network
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    image: wordpress:42
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception-network
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    image: mariadb:42
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception-network
    restart: unless-stopped

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /data/mariadb_data
      o: bind
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      device: /data/wordpress_data
      o: bind

networks:
    inception-network:
      name: inception-network

