version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx:42
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
      args:
        NGINX_HOST_DOMAIN: ${NGINX_HOST_DOMAIN} 
    init: true
    ports:
      - "443:443"
    volumes:                 
      - ./requirements/nginx/conf:/etc/nginx/conf.d  # Nginx configuration
      - ./requirements/nginx/html:/www  # Static HTML files
    env_file:
      - .env
    networks:
      - inception-network
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    image: wordpress:42
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception-network
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    image: mariadb:42
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception-network
    restart: unless-stopped

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /data/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /data/wordpress
      o: bind

networks:
  inception-network:
    name: inception-network

